### ISSUE TITLE
Create Cloud Architecture Design

### ISSUE THREAD

**Issue by msc117** [msc117/kraken#8]

**Comment by larisprengel** [comment]
![KRAKEN-aws-design](https://user-images.githubusercontent.com/69440907/89807105-ef4a9180-daec-11ea-84e2-addc01990bf8.png)
Closes #8

**Comment by larisprengel** [comment]
Closes #8
![KRAKEN-aws-design](https://user-images.githubusercontent.com/69440907/89807398-67b15280-daed-11ea-9ca2-9b2c07c5879b.png)

**Comment by larisprengel** [comment]
Closes #8 
![KRAKEN-aws-design](https://user-images.githubusercontent.com/69440907/89808376-e955b000-daee-11ea-80b8-fc626b9461bc.png)
